install:
	yay -S gnu-free-fonts gsfonts nerd-fonts-fira-code noto-fonts noto-fonts-emoji ttf-dejavu ttf-droid ttf-hack ttf-inconsolata ttf-joypixels ttf-liberation ttf-nerd-fonts-symbols ttf-twemoji-color ttf-wps-fonts wqy-microhei wqy-microhei-lite wqy-bitmapfont xorg-fonts-100dpi xorg-fonts-75dpi 

uninstall:
	sudo pacman -R gnu-free-fonts gsfonts nerd-fonts-fira-code noto-fonts noto-fonts-emoji ttf-dejavu ttf-droid ttf-hack ttf-inconsolata ttf-joypixels ttf-liberation ttf-nerd-fonts-symbols ttf-twemoji-color ttf-wps-fonts wqy-microhei wqy-microhei-lite wqy-bitmapfont xorg-fonts-100dpi xorg-fonts-75dpi

clean:
	yay -Scc

