
install-plasma:
	sudo pacman -S plasma kde-applications

install-sddm:
	sudo pacman -S sddm sddm-kcm
	sudo systemctl enable sddm

install-all:
	sudo pacman -S plasma kde-applications sddm sddm-kcm
	sudo systemctl enable sddm
